# Generated by Django 5.0.4 on 2024-04-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apimeta_api_method_alter_apimeta_api_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimeta',
            name='dj_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_meta', to='core.table'),
        ),
        migrations.AddField(
            model_name='field',
            name='dj_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.table'),
        ),
    ]
