# Generated by Django 5.0.4 on 2024-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apimeta_dj_table_field_dj_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimeta',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
