# Generated by Django 5.0.4 on 2024-04-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apimeta_original_id_field_original_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimeta',
            name='dj_table',
        ),
    ]
