# Generated by Django 5.0.4 on 2024-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_apimeta_api_name_alter_apimeta_psk_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='db_imports/%Y-%m-%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
