# Generated by Django 5.0.4 on 2024-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dbimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbimport',
            name='file',
            field=models.FileField(upload_to='db_imports/%d-%m-%Y/'),
        ),
    ]
