""""country"

Revision ID: 0001da589825
Revises: c35c20beb763
Create Date: 2024-02-15 15:59:37.958761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001da589825'
down_revision: Union[str, None] = 'c35c20beb763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_studio_app_group', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('api_studio_app_name', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('assignmenu_roleprivilege', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('country', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('country_media', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('country_media', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('country_media', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('country_post', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('country_post', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('country_post', sa.Column('file_blob', sa.LargeBinary(), nullable=True))
    op.add_column('country_post', sa.Column('file_mime', sa.String(), nullable=True))
    op.add_column('country_post', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('country_post', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('country_post_reaction', sa.Column('post_psk_id', sa.Integer(), nullable=True))
    op.add_column('country_post_reaction', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('country_post_reaction', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'country_post_reaction', 'country_post', ['post_psk_id'], ['psk_id'])
    op.add_column('gmc1201_01_01', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('gmc1202_01_01', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('gmc1203_01_01', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('gmc1204_01_01', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('gmc1208_01_01', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('kommunityapi', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('menus', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('menus_history', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('name', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('name_media', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('name_media', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('name_media', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('product', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('roleprivileges', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('saas_application', sa.Column('cdn_location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cdn_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cdn_location')
    op.drop_column('saas_application', 'cdn_location')
    op.drop_column('roles', 'cdn_location')
    op.drop_column('roleprivileges', 'cdn_location')
    op.drop_column('product', 'cdn_location')
    op.drop_column('name_media', 'file_path')
    op.drop_column('name_media', 'user_id')
    op.drop_column('name_media', 'app_id')
    op.drop_column('name', 'cdn_location')
    op.drop_column('menus_history', 'cdn_location')
    op.drop_column('menus', 'cdn_location')
    op.drop_column('kommunityapi', 'cdn_location')
    op.drop_column('gmc1208_01_01', 'cdn_location')
    op.drop_column('gmc1204_01_01', 'cdn_location')
    op.drop_column('gmc1203_01_01', 'cdn_location')
    op.drop_column('gmc1202_01_01', 'cdn_location')
    op.drop_column('gmc1201_01_01', 'cdn_location')
    op.drop_constraint(None, 'country_post_reaction', type_='foreignkey')
    op.drop_column('country_post_reaction', 'user_id')
    op.drop_column('country_post_reaction', 'app_id')
    op.drop_column('country_post_reaction', 'post_psk_id')
    op.drop_column('country_post', 'file_path')
    op.drop_column('country_post', 'file_name')
    op.drop_column('country_post', 'file_mime')
    op.drop_column('country_post', 'file_blob')
    op.drop_column('country_post', 'user_id')
    op.drop_column('country_post', 'app_id')
    op.drop_column('country_media', 'file_path')
    op.drop_column('country_media', 'user_id')
    op.drop_column('country_media', 'app_id')
    op.drop_column('country', 'cdn_location')
    op.drop_column('assignmenu_roleprivilege', 'cdn_location')
    op.drop_column('api_studio_app_name', 'cdn_location')
    op.drop_column('api_studio_app_group', 'cdn_location')
    # ### end Alembic commands ###
