"""sc_01_company_users

Revision ID: 024f10e3d833
Revises: 097556f381aa
Create Date: 2024-07-12 14:36:31.172919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024f10e3d833'
down_revision: Union[str, None] = '097556f381aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sc_01_company_users', sa.Column('user_post', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sc_01_company_users', 'user_post')
    # ### end Alembic commands ###
