"""cmspageupdate

Revision ID: 02c61a23fc78
Revises: 06b7b392ad3d
Create Date: 2024-03-16 15:30:54.634821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c61a23fc78'
down_revision: Union[str, None] = '06b7b392ad3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_cms_logs', sa.Column('api_action', sa.String(), nullable=True))
    op.add_column('api_cms_page', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_cms_page', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_cms_page', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('api_cms_page', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_cms_page', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_cms_page_migrations', 'updated_on')
    op.drop_column('api_cms_page_migrations', 'updated_by')
    op.drop_column('api_cms_page_migrations', 'created_on')
    op.drop_column('api_cms_page_migrations', 'created_by')
    op.drop_column('api_cms_page_migrations', 'user_id')
    op.drop_column('api_cms_page', 'updated_on')
    op.drop_column('api_cms_page', 'updated_by')
    op.drop_column('api_cms_page', 'created_on')
    op.drop_column('api_cms_page', 'created_by')
    op.drop_column('api_cms_page', 'user_id')
    op.drop_column('api_cms_logs', 'api_action')
    # ### end Alembic commands ###
