"""sc_01_company_users

Revision ID: 0467a57415ce
Revises: 463df9e3e02b
Create Date: 2024-06-27 12:23:14.486170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0467a57415ce'
down_revision: Union[str, None] = '463df9e3e02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sc_01_company_users', sa.Column('sc_01_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sc_01_company_users', 'sc_01_company', ['sc_01_company_id'], ['psk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sc_01_company_users', type_='foreignkey')
    op.drop_column('sc_01_company_users', 'sc_01_company_id')
    # ### end Alembic commands ###
