""""asa0204_01_01"

Revision ID: 06b7b392ad3d
Revises: a4ae9ebcdf01
Create Date: 2024-03-15 09:33:52.430460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b7b392ad3d'
down_revision: Union[str, None] = 'a4ae9ebcdf01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asa0204_01_01_media',
    sa.Column('psk_id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('parent_psk_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.String(), nullable=True),
    sa.Column('cancel_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_status', sa.String(), nullable=True),
    sa.Column('cancel_remarks', sa.String(), nullable=True),
    sa.Column('attachment_content', sa.Text(), nullable=True),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.Column('file_mime', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('gis_latitude', sa.Float(), nullable=True),
    sa.Column('gis_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_psk_id'], ['asa0204_01_01.psk_id'], ),
    sa.PrimaryKeyConstraint('psk_id')
    )
    op.create_index(op.f('ix_asa0204_01_01_media_psk_id'), 'asa0204_01_01_media', ['psk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asa0204_01_01_media_psk_id'), table_name='asa0204_01_01_media')
    op.drop_table('asa0204_01_01_media')
    # ### end Alembic commands ###
