"""helpdesk_website_logo

Revision ID: 087d3aa1d96a
Revises: 428da94db97d
Create Date: 2024-05-31 13:58:27.397472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087d3aa1d96a'
down_revision: Union[str, None] = '428da94db97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('helpdesk_website_logo', sa.Column('website_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('helpdesk_website_logo', 'website_version')
    # ### end Alembic commands ###
