""""gmc1208_01_01"

Revision ID: 0880980ce2dc
Revises: dfbb1d875ddb
Create Date: 2024-01-11 17:25:46.921115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0880980ce2dc'
down_revision: Union[str, None] = 'dfbb1d875ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
