"""scemail

Revision ID: 097556f381aa
Revises: a9ad2b868c40
Create Date: 2024-07-09 16:20:44.393444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097556f381aa'
down_revision: Union[str, None] = 'a9ad2b868c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0201_01_01', 'user_role_privilege',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('asa0201_01_01', 'user_role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'asa0201_01_01', ['user_role'])
    op.alter_column('asa0203_01_01', 'active',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('asa0203_01_01', 'menu_privilege_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'asa0203_01_01', ['menu_privilege_name'])
    op.alter_column('asa0204_01_01', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'asa0204_01_01', ['username'])
    op.alter_column('asa0205_01_01', 'menu_privilege',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('asa0205_01_01', 'menu_items',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('asa0205_01_01', 'user_privilege_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'asa0205_01_01', ['user_privilege_name'])
    op.add_column('sc_01_company', sa.Column('company_emailid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sc_01_company', 'company_emailid')
    op.drop_constraint(None, 'asa0205_01_01', type_='unique')
    op.alter_column('asa0205_01_01', 'user_privilege_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asa0205_01_01', 'menu_items',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('asa0205_01_01', 'menu_privilege',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'asa0204_01_01', type_='unique')
    op.alter_column('asa0204_01_01', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'asa0203_01_01', type_='unique')
    op.alter_column('asa0203_01_01', 'menu_privilege_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asa0203_01_01', 'active',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'asa0201_01_01', type_='unique')
    op.alter_column('asa0201_01_01', 'user_role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asa0201_01_01', 'user_role_privilege',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
