"""db

Revision ID: 09e694872a72
Revises: 96fbd3cb3948
Create Date: 2024-03-27 15:34:53.141731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09e694872a72'
down_revision: Union[str, None] = '96fbd3cb3948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_psk_id', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('psk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('api_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('app_psk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('app_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('psk_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancel_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cancel_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancel_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cancel_remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approval_level_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_level_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_remarks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workflow_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gis_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gis_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cdn_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ref_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('psk_id', name='customer_pkey')
    )
    op.create_index('ix_customer_psk_id', 'customer', ['psk_id'], unique=False)
    # ### end Alembic commands ###
