"""am1

Revision ID: 0b41d5d363bd
Revises: ddb7793d7429
Create Date: 2024-09-18 11:18:35.152046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b41d5d363bd'
down_revision: Union[str, None] = 'ddb7793d7429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('am1', 't1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'am1', ['t1'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'am1', type_='unique')
    op.alter_column('am1', 't1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
