"""alter

Revision ID: 0f7f99ea09dd
Revises: 22314a449dfa
Create Date: 2024-10-03 10:38:13.763904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7f99ea09dd'
down_revision: Union[str, None] = '22314a449dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_sql_trace', 'updated_by')
    op.drop_column('api_sql_trace', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_sql_trace', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_sql_trace', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
