""""asa0203_01_01"

Revision ID: 1e3983b71435
Revises: 69d95c74cfd2
Create Date: 2024-03-20 14:34:05.801299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3983b71435'
down_revision: Union[str, None] = '69d95c74cfd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0201_01_01', 'dupcheck')
    op.drop_column('asa0202_01_01', 'visible')
    op.drop_column('asa0203_01_01', 'dupcheck')
    op.drop_column('asa0203_01_01', 'menu_privilege')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0203_01_01', sa.Column('menu_privilege', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0203_01_01', sa.Column('dupcheck', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0202_01_01', sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('asa0201_01_01', sa.Column('dupcheck', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
