"""Logs

Revision ID: 28396f001c07
Revises: 854659cf30c5
Create Date: 2024-03-01 17:44:37.107116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28396f001c07'
down_revision: Union[str, None] = '854659cf30c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_core_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_core_logs_id'), 'api_core_logs', ['id'], unique=False)
    op.create_table('api_core_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['api_core.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_core_migrations_id'), 'api_core_migrations', ['id'], unique=False)
    op.create_table('api_meta_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_meta_logs_id'), 'api_meta_logs', ['id'], unique=False)
    op.add_column('api_auth_token_generator', sa.Column('expiry_time', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_column('api_auth_token_generator', 'time')
    op.add_column('api_auth_token_generator_migrations', sa.Column('expiry_time', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_column('api_auth_token_generator_migrations', 'time')
    op.add_column('api_core', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('api_meta', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('api_models', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('table_name_public', sa.String(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('relations', sa.String(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('db_connection', sa.Integer(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('db_connection_name', sa.String(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('readonly', sa.Boolean(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('has_media', sa.Boolean(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('has_posts', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'api_models_migrations', 'api_connection', ['db_connection'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_models_migrations', type_='foreignkey')
    op.drop_column('api_models_migrations', 'has_posts')
    op.drop_column('api_models_migrations', 'has_media')
    op.drop_column('api_models_migrations', 'document_url')
    op.drop_column('api_models_migrations', 'readonly')
    op.drop_column('api_models_migrations', 'db_connection_name')
    op.drop_column('api_models_migrations', 'db_connection')
    op.drop_column('api_models_migrations', 'relations')
    op.drop_column('api_models_migrations', 'published')
    op.drop_column('api_models_migrations', 'table_name_public')
    op.drop_column('api_models', 'created_date')
    op.drop_column('api_meta', 'created_date')
    op.drop_column('api_core', 'created_date')
    op.add_column('api_auth_token_generator_migrations', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('api_auth_token_generator_migrations', 'created_on')
    op.drop_column('api_auth_token_generator_migrations', 'created_by')
    op.drop_column('api_auth_token_generator_migrations', 'expiry_time')
    op.add_column('api_auth_token_generator', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('api_auth_token_generator', 'created_on')
    op.drop_column('api_auth_token_generator', 'created_by')
    op.drop_column('api_auth_token_generator', 'expiry_time')
    op.drop_index(op.f('ix_api_meta_logs_id'), table_name='api_meta_logs')
    op.drop_table('api_meta_logs')
    op.drop_index(op.f('ix_api_core_migrations_id'), table_name='api_core_migrations')
    op.drop_table('api_core_migrations')
    op.drop_index(op.f('ix_api_core_logs_id'), table_name='api_core_logs')
    op.drop_table('api_core_logs')
    # ### end Alembic commands ###
