"""asa0202_01_01

Revision ID: 2875bbb7cf29
Revises: 087d3aa1d96a
Create Date: 2024-06-07 14:07:06.370145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2875bbb7cf29'
down_revision: Union[str, None] = '087d3aa1d96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('menu_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0202_01_01', 'menu_code')
    # ### end Alembic commands ###
