"""api_studio_app_group

Revision ID: 2bb7cd7dcb1c
Revises: a7916c90c005
Create Date: 2024-05-30 18:12:40.812812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb7cd7dcb1c'
down_revision: Union[str, None] = 'a7916c90c005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
