"""asa0202_01_01

Revision ID: 2bf9d1c228fa
Revises: 8e199e222b61
Create Date: 2024-06-24 14:50:23.914461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf9d1c228fa'
down_revision: Union[str, None] = '8e199e222b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('menu_parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0202_01_01', 'menu_parent_id')
    # ### end Alembic commands ###
