"""nms_server_status

Revision ID: 2c43fcd1dc71
Revises: 5ecdad0ebb98
Create Date: 2024-06-13 15:53:06.292081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c43fcd1dc71'
down_revision: Union[str, None] = '5ecdad0ebb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nms_server_status', sa.Column('active_server', sa.Integer(), nullable=True))
    op.add_column('nms_server_status', sa.Column('not_active_server', sa.Integer(), nullable=True))
    op.add_column('nms_server_status', sa.Column('last_uptime', sa.Date(), nullable=True))
    op.add_column('nms_server_status', sa.Column('last_down_time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nms_server_status', 'last_down_time')
    op.drop_column('nms_server_status', 'last_uptime')
    op.drop_column('nms_server_status', 'not_active_server')
    op.drop_column('nms_server_status', 'active_server')
    # ### end Alembic commands ###
