"""update

Revision ID: 2f41a65635bb
Revises: b26d7417718c
Create Date: 2024-03-06 16:52:24.994577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f41a65635bb'
down_revision: Union[str, None] = 'b26d7417718c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_cms_page_migrations', 'table_details')
    op.drop_column('api_cms_page_migrations', 'document_url')
    op.drop_column('api_cms_page_migrations', 'api_file')
    op.add_column('api_sql', sa.Column('api_header_requests', sa.Text(), nullable=True))
    op.add_column('api_sql', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_sql', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_sql', sa.Column('document_url', sa.String(), nullable=True))
    op.drop_column('api_sql', 'api_body_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_sql', sa.Column('api_body_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('api_sql', 'document_url')
    op.drop_column('api_sql', 'api_header_property')
    op.drop_column('api_sql', 'api_header')
    op.drop_column('api_sql', 'api_header_requests')
    op.add_column('api_cms_page_migrations', sa.Column('api_file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('document_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('table_details', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
