"""am

Revision ID: 33f3a7e7299a
Revises: 524eef528b3a
Create Date: 2024-09-10 17:17:23.543494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f3a7e7299a'
down_revision: Union[str, None] = '524eef528b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('am', sa.Column('sample2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('am', 'sample2')
    # ### end Alembic commands ###
