"""helpdesk_website_logo

Revision ID: 372a505325ca
Revises: 2bb7cd7dcb1c
Create Date: 2024-05-30 19:02:46.045255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372a505325ca'
down_revision: Union[str, None] = '2bb7cd7dcb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
