"""authtable

Revision ID: 376bce88f497
Revises: 7d4de4d486e9
Create Date: 2024-04-02 14:21:54.959068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376bce88f497'
down_revision: Union[str, None] = '7d4de4d486e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth_token_generator', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('db_connection', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('db_connection_name', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_name', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_type', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_method', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_property', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_header_requests', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('expiry_duration', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('expiry_rules', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('expiry_property', sa.Text(), nullable=True))
    op.drop_column('api_auth_token_generator', 'expiry_time')
    op.add_column('api_auth_token_generator_logs', sa.Column('table_id', sa.Integer(), nullable=True))
    op.drop_constraint('api_auth_token_generator_logs_token_id_fkey', 'api_auth_token_generator_logs', type_='foreignkey')
    op.create_foreign_key(None, 'api_auth_token_generator_logs', 'api_auth_token_generator', ['table_id'], ['id'])
    op.drop_column('api_auth_token_generator_logs', 'token_id')
    op.drop_column('api_auth_token_generator_logs', 'psk_uid')
    op.add_column('api_auth_token_generator_migrations', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('db_connection', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('db_connection_name', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_name', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_type', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_method', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_property', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_header_requests', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('expiry_duration', sa.Integer(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('expiry_rules', sa.Text(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('expiry_property', sa.Text(), nullable=True))
    op.drop_constraint('api_auth_token_generator_migrations_token_id_fkey', 'api_auth_token_generator_migrations', type_='foreignkey')
    op.create_foreign_key(None, 'api_auth_token_generator_migrations', 'api_auth_token_generator', ['table_id'], ['id'])
    op.drop_column('api_auth_token_generator_migrations', 'token_id')
    op.drop_column('api_auth_token_generator_migrations', 'expiry_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth_token_generator_migrations', sa.Column('expiry_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_auth_token_generator_migrations', type_='foreignkey')
    op.create_foreign_key('api_auth_token_generator_migrations_token_id_fkey', 'api_auth_token_generator_migrations', 'api_auth_token_generator', ['token_id'], ['id'])
    op.drop_column('api_auth_token_generator_migrations', 'expiry_property')
    op.drop_column('api_auth_token_generator_migrations', 'expiry_rules')
    op.drop_column('api_auth_token_generator_migrations', 'expiry_duration')
    op.drop_column('api_auth_token_generator_migrations', 'api_header_requests')
    op.drop_column('api_auth_token_generator_migrations', 'api_header_property')
    op.drop_column('api_auth_token_generator_migrations', 'api_header')
    op.drop_column('api_auth_token_generator_migrations', 'api_property')
    op.drop_column('api_auth_token_generator_migrations', 'api_method')
    op.drop_column('api_auth_token_generator_migrations', 'api_type')
    op.drop_column('api_auth_token_generator_migrations', 'api_name')
    op.drop_column('api_auth_token_generator_migrations', 'db_connection_name')
    op.drop_column('api_auth_token_generator_migrations', 'db_connection')
    op.drop_column('api_auth_token_generator_migrations', 'document_url')
    op.drop_column('api_auth_token_generator_migrations', 'updated_on')
    op.drop_column('api_auth_token_generator_migrations', 'updated_by')
    op.drop_column('api_auth_token_generator_migrations', 'user_id')
    op.drop_column('api_auth_token_generator_migrations', 'table_id')
    op.add_column('api_auth_token_generator_logs', sa.Column('psk_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_auth_token_generator_logs', sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_auth_token_generator_logs', type_='foreignkey')
    op.create_foreign_key('api_auth_token_generator_logs_token_id_fkey', 'api_auth_token_generator_logs', 'api_auth_token_generator', ['token_id'], ['id'])
    op.drop_column('api_auth_token_generator_logs', 'table_id')
    op.add_column('api_auth_token_generator', sa.Column('expiry_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('api_auth_token_generator', 'expiry_property')
    op.drop_column('api_auth_token_generator', 'expiry_rules')
    op.drop_column('api_auth_token_generator', 'expiry_duration')
    op.drop_column('api_auth_token_generator', 'api_header_requests')
    op.drop_column('api_auth_token_generator', 'api_header_property')
    op.drop_column('api_auth_token_generator', 'api_header')
    op.drop_column('api_auth_token_generator', 'api_property')
    op.drop_column('api_auth_token_generator', 'api_method')
    op.drop_column('api_auth_token_generator', 'api_type')
    op.drop_column('api_auth_token_generator', 'api_name')
    op.drop_column('api_auth_token_generator', 'db_connection_name')
    op.drop_column('api_auth_token_generator', 'db_connection')
    op.drop_column('api_auth_token_generator', 'document_url')
    op.drop_column('api_auth_token_generator', 'updated_on')
    op.drop_column('api_auth_token_generator', 'updated_by')
    op.drop_column('api_auth_token_generator', 'user_id')
    # ### end Alembic commands ###
