"""nsm_server_log

Revision ID: 3820021aa1a4
Revises: 98c5bb68f3cd
Create Date: 2024-06-12 11:37:04.687680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3820021aa1a4'
down_revision: Union[str, None] = '98c5bb68f3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
