"""authfieldchange

Revision ID: 38b535f1de24
Revises: bfb71a3da2f4
Create Date: 2024-04-03 16:06:02.172227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b535f1de24'
down_revision: Union[str, None] = 'bfb71a3da2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth_token_generator', sa.Column('uid', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('api_source', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('secret_key_start_datetime', sa.DateTime(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('uid', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('api_source', sa.String(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('secret_key_start_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_auth_token_generator_migrations', 'secret_key_start_datetime')
    op.drop_column('api_auth_token_generator_migrations', 'api_source')
    op.drop_column('api_auth_token_generator_migrations', 'uid')
    op.drop_column('api_auth_token_generator', 'secret_key_start_datetime')
    op.drop_column('api_auth_token_generator', 'api_source')
    op.drop_column('api_auth_token_generator', 'uid')
    # ### end Alembic commands ###
