""""api_studio_app_name"

Revision ID: 3ab8011afecf
Revises: 0880980ce2dc
Create Date: 2024-01-24 14:23:27.886815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab8011afecf'
down_revision: Union[str, None] = '0880980ce2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_studio_app_name', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_studio_app_name', 'used')
    # ### end Alembic commands ###
