"""asa0204_01_01

Revision ID: 3d143f1e9042
Revises: 50b48d54de7d
Create Date: 2024-08-12 10:44:30.749216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d143f1e9042'
down_revision: Union[str, None] = '50b48d54de7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0204_01_01', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0204_01_01', 'active')
    # ### end Alembic commands ###
