"""am

Revision ID: 3dbddf58ed7d
Revises: c75cc1331dd7
Create Date: 2024-09-10 12:17:48.658825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbddf58ed7d'
down_revision: Union[str, None] = 'c75cc1331dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('am', sa.Column('demo2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('am', 'demo2')
    # ### end Alembic commands ###
