"""testing_tbl11

Revision ID: 46b6cfa49f2e
Revises: 0b41d5d363bd
Create Date: 2024-09-20 18:02:53.735523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b6cfa49f2e'
down_revision: Union[str, None] = '0b41d5d363bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
