""""asa0202_01_01"

Revision ID: 496b73ba591a
Revises: 41c02942bc10
Create Date: 2024-03-19 10:53:29.656712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496b73ba591a'
down_revision: Union[str, None] = '41c02942bc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0202_01_01', 'level_no')
    op.drop_column('asa0202_01_01', 'ord_no')
    op.drop_column('asa0202_01_01', 'dupcheck')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('dupcheck', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0202_01_01', sa.Column('ord_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('asa0202_01_01', sa.Column('level_no', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
