"""helpdesk_website_logo

Revision ID: 501bc0d6b95c
Revises: fc6505205f63
Create Date: 2024-05-30 14:43:16.467057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501bc0d6b95c'
down_revision: Union[str, None] = 'fc6505205f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
