"""asa0205_01_01

Revision ID: 50b48d54de7d
Revises: 637e8f14c209
Create Date: 2024-08-03 14:19:20.617540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b48d54de7d'
down_revision: Union[str, None] = '637e8f14c209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0205_01_01', 'user_privilege_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('asa0205_01_01_user_privilege_name_key', 'asa0205_01_01', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('asa0205_01_01_user_privilege_name_key', 'asa0205_01_01', ['user_privilege_name'])
    op.alter_column('asa0205_01_01', 'user_privilege_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
