"""sc_01_category

Revision ID: 50cbe2d7d4de
Revises: 2bf9d1c228fa
Create Date: 2024-06-27 12:20:49.216853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cbe2d7d4de'
down_revision: Union[str, None] = '2bf9d1c228fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0202_01_01', 'menu_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0202_01_01', 'menu_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
