"""cmspagelog

Revision ID: 510295f53ac2
Revises: 5c7be9a5a2d3
Create Date: 2024-03-14 15:24:10.016093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '510295f53ac2'
down_revision: Union[str, None] = '5c7be9a5a2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_model_migrations_id', table_name='api_model_migrations')
    op.drop_table('api_model_migrations')
    op.add_column('api_cms_page', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_connection', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_schema', sa.Column('psk_uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_schema', 'psk_uid')
    op.drop_column('api_connection', 'psk_uid')
    op.drop_column('api_cms_page_migrations', 'psk_uid')
    op.drop_column('api_cms_page', 'psk_uid')
    op.create_table('api_model_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_models.id'], name='api_model_migrations_table_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_model_migrations_pkey')
    )
    op.create_index('ix_api_model_migrations_id', 'api_model_migrations', ['id'], unique=False)
    # ### end Alembic commands ###
