"""api_hcas_onlinepayment

Revision ID: 537e40a7c4a5
Revises: f0de9d350523
Create Date: 2024-06-20 13:04:12.363640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537e40a7c4a5'
down_revision: Union[str, None] = 'f0de9d350523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
