"""asa0202_01_01

Revision ID: 56145d2ffddd
Revises: f7d64309895f
Create Date: 2024-03-28 17:05:09.057381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56145d2ffddd'
down_revision: Union[str, None] = 'f7d64309895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('menu_app_bar', sa.String(), nullable=True))
    op.add_column('asa0202_01_01', sa.Column('menu_psk_uid', sa.String(), nullable=True))
    op.add_column('asa0202_01_01', sa.Column('menu_psk_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0202_01_01', 'menu_psk_id')
    op.drop_column('asa0202_01_01', 'menu_psk_uid')
    op.drop_column('asa0202_01_01', 'menu_app_bar')
    # ### end Alembic commands ###
