"""30.01.2024 update

Revision ID: 5795852ba75b
Revises: 746354a88fbf
Create Date: 2024-01-30 15:41:19.029752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5795852ba75b'
down_revision: Union[str, None] = '746354a88fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_core', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('api_meta', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('api_meta_migrations', sa.Column('document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_meta_migrations', 'document_url')
    op.drop_column('api_meta', 'document_url')
    op.drop_column('api_core', 'document_url')
    # ### end Alembic commands ###
