"""asa0201_01_01

Revision ID: 6169d135e9f2
Revises: c2a63b0b8aef
Create Date: 2024-04-04 10:49:20.493253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6169d135e9f2'
down_revision: Union[str, None] = 'c2a63b0b8aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0201_01_01', 'user_group_type')
    op.drop_column('asa0201_01_01', 'user_group_Name')
    op.drop_column('asa0201_01_01', 'user_privilege')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0201_01_01', sa.Column('user_privilege', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0201_01_01', sa.Column('user_group_Name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0201_01_01', sa.Column('user_group_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
