"""sc_01_post

Revision ID: 6520dd012dbd
Revises: 3994590b5581
Create Date: 2024-07-18 13:04:17.637651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6520dd012dbd'
down_revision: Union[str, None] = '3994590b5581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sc_01_post', sa.Column('company', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sc_01_post', 'company')
    # ### end Alembic commands ###
