"""sc_01_post

Revision ID: 6681c43d5403
Revises: 813e4b7357fd
Create Date: 2024-07-15 17:36:59.235018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6681c43d5403'
down_revision: Union[str, None] = '813e4b7357fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sc_01_post', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sc_01_post', 'department')
    # ### end Alembic commands ###
