"""sc_01_sub_category

Revision ID: 68d005c4cdc3
Revises: f58df7a7c10c
Create Date: 2024-06-28 18:10:58.220953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d005c4cdc3'
down_revision: Union[str, None] = 'f58df7a7c10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sc_01_category', 'category_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'sc_01_category', ['category_code'])
    op.alter_column('sc_01_company', 'company_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'sc_01_company', ['company_code'])
    op.alter_column('sc_01_uom', 'uom_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sc_01_uom', 'active',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sc_01_uom', 'uom_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'sc_01_uom', ['uom_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sc_01_uom', type_='unique')
    op.alter_column('sc_01_uom', 'uom_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sc_01_uom', 'active',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sc_01_uom', 'uom_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'sc_01_company', type_='unique')
    op.alter_column('sc_01_company', 'company_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'sc_01_category', type_='unique')
    op.alter_column('sc_01_category', 'category_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
