"""asa0202_01_01

Revision ID: 69cfd3c16bc6
Revises: daecd82fd03d
Create Date: 2024-03-28 16:36:31.418871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cfd3c16bc6'
down_revision: Union[str, None] = 'daecd82fd03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
