""""asa0203_01_01"

Revision ID: 69d95c74cfd2
Revises: 795527901081
Create Date: 2024-03-20 14:18:07.851168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d95c74cfd2'
down_revision: Union[str, None] = '795527901081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('active', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('active', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_name', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_app_bar', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_type', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_href', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_dropdown', sa.String(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_icon', sa.String(), nullable=True))
    op.alter_column('asa0204_01_01', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0204_01_01', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('asa0203_01_01', 'menu_privilege_icon')
    op.drop_column('asa0203_01_01', 'menu_privilege_dropdown')
    op.drop_column('asa0203_01_01', 'menu_privilege_href')
    op.drop_column('asa0203_01_01', 'menu_privilege_type')
    op.drop_column('asa0203_01_01', 'menu_app_bar')
    op.drop_column('asa0203_01_01', 'menu_privilege_name')
    op.drop_column('asa0203_01_01', 'active')
    op.drop_column('asa0202_01_01', 'active')
    # ### end Alembic commands ###
