""""country"

Revision ID: 72fd7087c667
Revises: 73b50ac6a535
Create Date: 2024-02-03 22:43:15.718913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fd7087c667'
down_revision: Union[str, None] = '73b50ac6a535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_media',
    sa.Column('psk_id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.String(), nullable=True),
    sa.Column('cancel_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_status', sa.String(), nullable=True),
    sa.Column('cancel_remarks', sa.String(), nullable=True),
    sa.Column('attachment_content', sa.Text(), nullable=True),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.Column('file_mime', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('gis_latitude', sa.Float(), nullable=True),
    sa.Column('gis_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['country.psk_id'], ),
    sa.PrimaryKeyConstraint('psk_id')
    )
    op.create_index(op.f('ix_country_media_psk_id'), 'country_media', ['psk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_media_psk_id'), table_name='country_media')
    op.drop_table('country_media')
    # ### end Alembic commands ###
