"""MEDIA TABLE

Revision ID: 73b50ac6a535
Revises: 5795852ba75b
Create Date: 2024-02-02 17:16:01.087815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b50ac6a535'
down_revision: Union[str, None] = '5795852ba75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cms_page_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_details', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('api_source', sa.String(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('python_file', sa.LargeBinary(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('api_property', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection'], ['api_connection.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['api_cms_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_cms_page_migrations_id'), 'api_cms_page_migrations', ['id'], unique=False)
    op.add_column('api_models', sa.Column('has_media', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_models', 'has_media')
    op.drop_index(op.f('ix_api_cms_page_migrations_id'), table_name='api_cms_page_migrations')
    op.drop_table('api_cms_page_migrations')
    # ### end Alembic commands ###
