""""gmc1203_01_01"

Revision ID: 73bbc3bf164e
Revises: 73d6cb258056
Create Date: 2023-12-23 11:22:28.761711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bbc3bf164e'
down_revision: Union[str, None] = '73d6cb258056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
