"""demo7

Revision ID: 73c36aed446e
Revises: ba96c32c3bba
Create Date: 2024-06-14 17:19:35.834979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c36aed446e'
down_revision: Union[str, None] = 'ba96c32c3bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0202_01_01', 'menu_code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('asa0204_01_01', 'user_type')
    op.add_column('country', sa.Column('demo7', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'demo7')
    op.add_column('asa0204_01_01', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('asa0202_01_01', 'menu_code',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
