""""api_studio_app_group"

Revision ID: 746354a88fbf
Revises: 3ab8011afecf
Create Date: 2024-01-27 14:21:10.706554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746354a88fbf'
down_revision: Union[str, None] = '3ab8011afecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_studio_app_group', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('api_studio_app_group', sa.Column('child', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_studio_app_group', 'child')
    op.drop_column('api_studio_app_group', 'parent_id')
    # ### end Alembic commands ###
