"""fieldchange

Revision ID: 781a4025330d
Revises: 09e694872a72
Create Date: 2024-03-27 16:31:17.904358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781a4025330d'
down_revision: Union[str, None] = '09e694872a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_core', sa.Column('api_code_name', sa.Text(), nullable=True))
    op.add_column('api_core', sa.Column('api_code_file', sa.LargeBinary(), nullable=True))
    op.add_column('api_core', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_core', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_core', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('api_core', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_core', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('api_core', 'python_code')
    op.add_column('api_core_migrations', sa.Column('api_code_name', sa.Text(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('api_code_file', sa.LargeBinary(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('api_core_migrations', 'python_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_core_migrations', sa.Column('python_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('api_core_migrations', 'updated_on')
    op.drop_column('api_core_migrations', 'updated_by')
    op.drop_column('api_core_migrations', 'created_on')
    op.drop_column('api_core_migrations', 'created_by')
    op.drop_column('api_core_migrations', 'user_id')
    op.drop_column('api_core_migrations', 'api_code_file')
    op.drop_column('api_core_migrations', 'api_code_name')
    op.add_column('api_core', sa.Column('python_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('api_core', 'updated_on')
    op.drop_column('api_core', 'updated_by')
    op.drop_column('api_core', 'created_on')
    op.drop_column('api_core', 'created_by')
    op.drop_column('api_core', 'user_id')
    op.drop_column('api_core', 'api_code_file')
    op.drop_column('api_core', 'api_code_name')
    # ### end Alembic commands ###
