"""apijobs2

Revision ID: 7959937a3dbf
Revises: fdb668e2c26a
Create Date: 2024-12-31 11:35:31.879342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7959937a3dbf'
down_revision: Union[str, None] = 'fdb668e2c26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_jobs', sa.Column('last_executed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_jobs', 'last_executed_on')
    # ### end Alembic commands ###
