"""am

Revision ID: 7a6b3a986cf8
Revises: 3dbddf58ed7d
Create Date: 2024-09-10 12:18:52.558149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6b3a986cf8'
down_revision: Union[str, None] = '3dbddf58ed7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('am', sa.Column('demo3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('am', 'demo3')
    # ### end Alembic commands ###
