"""authactive

Revision ID: 7d4de4d486e9
Revises: c8c3d16b1cab
Create Date: 2024-04-01 17:29:25.407720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4de4d486e9'
down_revision: Union[str, None] = 'c8c3d16b1cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth_token_generator', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_auth_token_generator_migrations', 'active')
    op.drop_column('api_auth_token_generator', 'active')
    # ### end Alembic commands ###
