"""gmc177007

Revision ID: 7d96b8832c7a
Revises: 46b6cfa49f2e
Create Date: 2024-09-20 18:08:03.403283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d96b8832c7a'
down_revision: Union[str, None] = '46b6cfa49f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('am1', sa.Column('t3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('am1', 't3')
    # ### end Alembic commands ###
