"""cmscoresql

Revision ID: 8363f4fa6b40
Revises: 0111e3f3edbc
Create Date: 2024-04-04 11:51:13.563874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8363f4fa6b40'
down_revision: Union[str, None] = '0111e3f3edbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_cms_page', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_cms_page', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_cms_page', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_cms_page', sa.Column('api_header_requests', sa.Text(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_cms_page_migrations', sa.Column('api_header_requests', sa.Text(), nullable=True))
    op.add_column('api_core', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_core', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_core', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('api_header', sa.Text(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('api_header_property', sa.Text(), nullable=True))
    op.add_column('api_sql', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_sql', sa.Column('api_property', sa.Text(), nullable=True))
    op.add_column('api_sql', sa.Column('api_source', sa.String(), nullable=True))
    op.add_column('api_sql_migrations', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('api_sql_migrations', sa.Column('api_property', sa.Text(), nullable=True))
    op.add_column('api_sql_migrations', sa.Column('api_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_sql_migrations', 'api_source')
    op.drop_column('api_sql_migrations', 'api_property')
    op.drop_column('api_sql_migrations', 'active')
    op.drop_column('api_sql', 'api_source')
    op.drop_column('api_sql', 'api_property')
    op.drop_column('api_sql', 'active')
    op.drop_column('api_core_migrations', 'api_header_property')
    op.drop_column('api_core_migrations', 'api_header')
    op.drop_column('api_core_migrations', 'active')
    op.drop_column('api_core', 'api_header_property')
    op.drop_column('api_core', 'api_header')
    op.drop_column('api_core', 'active')
    op.drop_column('api_cms_page_migrations', 'api_header_requests')
    op.drop_column('api_cms_page_migrations', 'api_header_property')
    op.drop_column('api_cms_page_migrations', 'api_header')
    op.drop_column('api_cms_page_migrations', 'active')
    op.drop_column('api_cms_page', 'api_header_requests')
    op.drop_column('api_cms_page', 'api_header_property')
    op.drop_column('api_cms_page', 'api_header')
    op.drop_column('api_cms_page', 'active')
    # ### end Alembic commands ###
