"""asa0204_01_01

Revision ID: 88fe12cbcefb
Revises: c7565471c550
Create Date: 2024-08-01 16:03:39.186910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fe12cbcefb'
down_revision: Union[str, None] = 'c7565471c550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0204_01_01', 'home_menu',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0204_01_01', 'home_menu',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
