"""asa0204_01_01

Revision ID: 8b663af6977c
Revises: a1b38d5a898c
Create Date: 2024-03-28 17:33:56.485312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b663af6977c'
down_revision: Union[str, None] = 'a1b38d5a898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0204_01_01', 'user_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0204_01_01', sa.Column('user_groups', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
