"""nms_app_service_status

Revision ID: 8e199e222b61
Revises: 3d7b4462f00a
Create Date: 2024-06-20 16:52:06.163738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e199e222b61'
down_revision: Union[str, None] = '3d7b4462f00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nms_app_service_status', sa.Column('running_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nms_app_service_status', 'running_status')
    # ### end Alembic commands ###
