""""asa0202_01_01"

Revision ID: 900a7ddeb60e
Revises: 9a57a367c21a
Create Date: 2024-03-19 10:47:03.991381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900a7ddeb60e'
down_revision: Union[str, None] = '9a57a367c21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
