"""Post Reaction

Revision ID: 989a34b0dc0b
Revises: 72fd7087c667
Create Date: 2024-02-09 15:52:21.782232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989a34b0dc0b'
down_revision: Union[str, None] = '72fd7087c667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_models', sa.Column('has_posts', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_models', 'has_posts')
    # ### end Alembic commands ###
