"""homemenu

Revision ID: 98c5bb68f3cd
Revises: 2875bbb7cf29
Create Date: 2024-06-12 11:02:51.651628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c5bb68f3cd'
down_revision: Union[str, None] = '2875bbb7cf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0202_01_01', 'menu_code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('asa0204_01_01', sa.Column('home_menu', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0204_01_01', 'home_menu')
    op.alter_column('asa0202_01_01', 'menu_code',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
