""""asa0204_01_01"

Revision ID: 99872de3a9dc
Revises: 963b364043c9
Create Date: 2024-03-21 14:08:56.105493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99872de3a9dc'
down_revision: Union[str, None] = '963b364043c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asa0204_01_01_post',
    sa.Column('psk_id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('parent_psk_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('post_comment', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.String(), nullable=True),
    sa.Column('cancel_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_status', sa.String(), nullable=True),
    sa.Column('cancel_remarks', sa.String(), nullable=True),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.Column('file_mime', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('gis_latitude', sa.Float(), nullable=True),
    sa.Column('gis_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_psk_id'], ['asa0204_01_01.psk_id'], ),
    sa.PrimaryKeyConstraint('psk_id')
    )
    op.create_index(op.f('ix_asa0204_01_01_post_psk_id'), 'asa0204_01_01_post', ['psk_id'], unique=False)
    op.create_table('asa0204_01_01_post_reaction',
    sa.Column('psk_id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('parent_psk_id', sa.Integer(), nullable=True),
    sa.Column('post_psk_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.String(), nullable=True),
    sa.Column('cancel_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_status', sa.String(), nullable=True),
    sa.Column('cancel_remarks', sa.String(), nullable=True),
    sa.Column('gis_latitude', sa.Float(), nullable=True),
    sa.Column('gis_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_psk_id'], ['asa0204_01_01.psk_id'], ),
    sa.ForeignKeyConstraint(['post_psk_id'], ['asa0204_01_01_post.psk_id'], ),
    sa.PrimaryKeyConstraint('psk_id')
    )
    op.create_index(op.f('ix_asa0204_01_01_post_reaction_psk_id'), 'asa0204_01_01_post_reaction', ['psk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asa0204_01_01_post_reaction_psk_id'), table_name='asa0204_01_01_post_reaction')
    op.drop_table('asa0204_01_01_post_reaction')
    op.drop_index(op.f('ix_asa0204_01_01_post_psk_id'), table_name='asa0204_01_01_post')
    op.drop_table('asa0204_01_01_post')
    # ### end Alembic commands ###
