"""19UPDATE

Revision ID: 9a7499deefa7
Revises: 03b3a5b202d5
Create Date: 2023-12-19 11:21:47.458372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7499deefa7'
down_revision: Union[str, None] = '03b3a5b202d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_meta_migrations', sa.Column('uid', sa.String(), nullable=True))
    op.add_column('api_meta_migrations', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('api_meta_migrations', sa.Column('db_connection', sa.Integer(), nullable=True))
    op.add_column('api_meta_migrations', sa.Column('db_connection_name', sa.String(), nullable=True))
    op.add_column('api_meta_migrations', sa.Column('api_property', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'api_meta_migrations', 'api_connection', ['db_connection'], ['id'])
    op.create_foreign_key(None, 'api_meta_migrations', 'api_meta', ['table_id'], ['id'])
    op.add_column('api_model_migrations', sa.Column('uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_model_migrations', 'uid')
    op.drop_constraint(None, 'api_meta_migrations', type_='foreignkey')
    op.drop_constraint(None, 'api_meta_migrations', type_='foreignkey')
    op.drop_column('api_meta_migrations', 'api_property')
    op.drop_column('api_meta_migrations', 'db_connection_name')
    op.drop_column('api_meta_migrations', 'db_connection')
    op.drop_column('api_meta_migrations', 'table_id')
    op.drop_column('api_meta_migrations', 'uid')
    # ### end Alembic commands ###
