"""asa0205_01_01

Revision ID: 9c153b567aeb
Revises: 4f44e7ef9b22
Create Date: 2024-04-11 15:00:33.485613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c153b567aeb'
down_revision: Union[str, None] = '4f44e7ef9b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0205_01_01', sa.Column('user_privilege_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0205_01_01', 'user_privilege_name')
    # ### end Alembic commands ###
