"""apijobs5

Revision ID: 9daaf78899e7
Revises: 978d0d314d8f
Create Date: 2025-01-04 14:02:47.394287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9daaf78899e7'
down_revision: Union[str, None] = '978d0d314d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_jobs', sa.Column('api_base_url', sa.String(length=255), nullable=True))
    op.drop_column('api_jobs', 'core_api_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_jobs', sa.Column('core_api_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('api_jobs', 'api_base_url')
    # ### end Alembic commands ###
