"""basetablechange

Revision ID: 9e5ebae375ac
Revises: 99872de3a9dc
Create Date: 2024-03-21 17:58:03.192438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e5ebae375ac'
down_revision: Union[str, None] = '99872de3a9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_model_migrations_id', table_name='api_model_migrations')
    op.drop_table('api_model_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_model_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_models.id'], name='api_model_migrations_table_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_model_migrations_pkey')
    )
    op.create_index('ix_api_model_migrations_id', 'api_model_migrations', ['id'], unique=False)
    # ### end Alembic commands ###
