"""15latest

Revision ID: a151fa52a1b8
Revises: 1625db095f63
Create Date: 2024-06-15 10:41:17.534299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a151fa52a1b8'
down_revision: Union[str, None] = '1625db095f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0204_01_01', sa.Column('user_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0204_01_01', 'user_type')
    # ### end Alembic commands ###
