"""asa0203_01_01

Revision ID: a1b38d5a898c
Revises: 56145d2ffddd
Create Date: 2024-03-28 17:30:31.067502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b38d5a898c'
down_revision: Union[str, None] = '56145d2ffddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_grouping', sa.Text(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_start_date', sa.Date(), nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0203_01_01', 'menu_privilege_end_date')
    op.drop_column('asa0203_01_01', 'menu_privilege_start_date')
    op.drop_column('asa0203_01_01', 'menu_privilege_grouping')
    # ### end Alembic commands ###
