"""getpost

Revision ID: a4ae9ebcdf01
Revises: 510295f53ac2
Create Date: 2024-03-14 17:23:47.012608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ae9ebcdf01'
down_revision: Union[str, None] = '510295f53ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth_token_generator_logs', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_core', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_core', sa.Column('code_file', sa.LargeBinary(), nullable=True))
    op.add_column('api_core_logs', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('code_file', sa.LargeBinary(), nullable=True))
    op.add_column('api_fields', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_meta', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_meta_logs', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_meta_migrations', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_models', sa.Column('psk_uid', sa.String(), nullable=True))
    op.add_column('api_models_migrations', sa.Column('psk_uid', sa.String(), nullable=True))
    op.drop_constraint('api_studio_app_name_unkey', 'api_studio_app_name', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('api_studio_app_name_unkey', 'api_studio_app_name', ['app_id'])
    op.drop_column('api_models_migrations', 'psk_uid')
    op.drop_column('api_models', 'psk_uid')
    op.drop_column('api_meta_migrations', 'psk_uid')
    op.drop_column('api_meta_logs', 'psk_uid')
    op.drop_column('api_meta', 'psk_uid')
    op.drop_column('api_fields', 'psk_uid')
    op.drop_column('api_core_migrations', 'code_file')
    op.drop_column('api_core_migrations', 'psk_uid')
    op.drop_column('api_core_logs', 'psk_uid')
    op.drop_column('api_core', 'code_file')
    op.drop_column('api_core', 'psk_uid')
    op.drop_column('api_auth_token_generator_logs', 'psk_uid')
    # ### end Alembic commands ###
