"""alter2

Revision ID: a4b1813ff338
Revises: 0f7f99ea09dd
Create Date: 2024-10-03 10:52:59.293094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b1813ff338'
down_revision: Union[str, None] = '0f7f99ea09dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_sql', sa.Column('api_trace', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_sql', 'api_trace')
    # ### end Alembic commands ###
