"""country

Revision ID: a65ebfce48dc
Revises: 44796fc05e40
Create Date: 2024-05-10 13:33:07.034425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65ebfce48dc'
down_revision: Union[str, None] = '44796fc05e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('demo3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'demo3')
    # ### end Alembic commands ###
