"""sc_01_website_settings

Revision ID: a9ad2b868c40
Revises: 9a4a1be7899d
Create Date: 2024-07-02 11:03:55.475049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ad2b868c40'
down_revision: Union[str, None] = '9a4a1be7899d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
