"""fieldnameupd

Revision ID: ab0b176de887
Revises: 781a4025330d
Create Date: 2024-03-27 16:37:28.881073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0b176de887'
down_revision: Union[str, None] = '781a4025330d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_core', 'created_date')
    op.drop_column('api_core', 'code_name')
    op.drop_column('api_core', 'code_file')
    op.drop_column('api_core_migrations', 'created_date')
    op.drop_column('api_core_migrations', 'code_name')
    op.drop_column('api_core_migrations', 'code_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_core_migrations', sa.Column('code_file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('api_core_migrations', sa.Column('code_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_core_migrations', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('api_core', sa.Column('code_file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('api_core', sa.Column('code_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_core', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
