"""authfieldupdate

Revision ID: b2d2875048ba
Revises: 38b535f1de24
Create Date: 2024-04-03 16:13:32.855184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d2875048ba'
down_revision: Union[str, None] = '38b535f1de24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_auth_token_generator', 'source_key')
    op.drop_column('api_auth_token_generator', 'app_id')
    op.drop_column('api_auth_token_generator_migrations', 'source_key')
    op.drop_column('api_auth_token_generator_migrations', 'app_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_auth_token_generator_migrations', sa.Column('app_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_auth_token_generator_migrations', sa.Column('source_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('app_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_auth_token_generator', sa.Column('source_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
