"""login_users

Revision ID: b56cf3a6e610
Revises: 6520dd012dbd
Create Date: 2024-07-18 15:12:54.246999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56cf3a6e610'
down_revision: Union[str, None] = '6520dd012dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_users', sa.Column('company', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_users', 'company')
    # ### end Alembic commands ###
