"""nms_server_details

Revision ID: b5c610ad3633
Revises: 2c43fcd1dc71
Create Date: 2024-06-13 16:13:29.637622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c610ad3633'
down_revision: Union[str, None] = '2c43fcd1dc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nms_server_details', sa.Column('server_name', sa.String(), nullable=True))
    op.add_column('nms_server_details', sa.Column('server_system', sa.String(), nullable=True))
    op.add_column('nms_server_details', sa.Column('server_ram_size', sa.Integer(), nullable=True))
    op.add_column('nms_server_details', sa.Column('server_processor', sa.String(), nullable=True))
    op.add_column('nms_server_details', sa.Column('server_ip_addr', sa.Text(), nullable=True))
    op.add_column('nms_server_details', sa.Column('server_os_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nms_server_details', 'server_os_version')
    op.drop_column('nms_server_details', 'server_ip_addr')
    op.drop_column('nms_server_details', 'server_processor')
    op.drop_column('nms_server_details', 'server_ram_size')
    op.drop_column('nms_server_details', 'server_system')
    op.drop_column('nms_server_details', 'server_name')
    # ### end Alembic commands ###
