"""login_users

Revision ID: b67f1519fc7b
Revises: b56cf3a6e610
Create Date: 2024-07-18 15:13:34.737456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67f1519fc7b'
down_revision: Union[str, None] = 'b56cf3a6e610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_users', 'company',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login_users', 'company',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
