"""asa0205_01_01

Revision ID: bf6b1f4a2808
Revises: ccb820545fc6
Create Date: 2024-04-03 16:29:30.291938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6b1f4a2808'
down_revision: Union[str, None] = 'ccb820545fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0205_01_01', sa.Column('menu_items', sa.Text(), nullable=True))
    op.add_column('asa0205_01_01', sa.Column('menu_privilege', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0205_01_01', 'menu_privilege')
    op.drop_column('asa0205_01_01', 'menu_items')
    # ### end Alembic commands ###
