"""country

Revision ID: bfb71a3da2f4
Revises: 40a3741b49b2
Create Date: 2024-04-02 20:36:46.137916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb71a3da2f4'
down_revision: Union[str, None] = '40a3741b49b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('state', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'state')
    # ### end Alembic commands ###
