"""asa0205_01_01

Revision ID: c2a63b0b8aef
Revises: bf6b1f4a2808
Create Date: 2024-04-04 10:43:00.022912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a63b0b8aef'
down_revision: Union[str, None] = 'bf6b1f4a2808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0205_01_01', 'privilege_name')
    op.drop_column('asa0205_01_01', 'menu_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0205_01_01', sa.Column('menu_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0205_01_01', sa.Column('privilege_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
