""""asa0202_01_01"

Revision ID: c548e5e9e034
Revises: cd2e0ddb924b
Create Date: 2024-03-19 12:43:00.621507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c548e5e9e034'
down_revision: Union[str, None] = 'cd2e0ddb924b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('menu_level', sa.Integer(), nullable=True))
    op.add_column('asa0202_01_01', sa.Column('menu_order', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'asa0204_01_01', ['username'])
    op.create_unique_constraint(None, 'gmc1202_01_01', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gmc1202_01_01', type_='unique')
    op.drop_constraint(None, 'asa0204_01_01', type_='unique')
    op.drop_column('asa0202_01_01', 'menu_order')
    op.drop_column('asa0202_01_01', 'menu_level')
    # ### end Alembic commands ###
