"""sqlviewstable

Revision ID: c72f1707e56e
Revises: 1e3983b71435
Create Date: 2024-03-20 15:57:29.038920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c72f1707e56e'
down_revision: Union[str, None] = '1e3983b71435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_sql_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('api_action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_sql.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sql_logs_id'), 'api_sql_logs', ['id'], unique=False)
    op.create_table('api_sql_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('api_method', sa.String(), nullable=True),
    sa.Column('db_connection', sa.Integer(), nullable=True),
    sa.Column('db_connection_name', sa.String(), nullable=True),
    sa.Column('api_schema', sa.String(), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('api_header_requests', sa.Text(), nullable=True),
    sa.Column('api_header', sa.Text(), nullable=True),
    sa.Column('api_header_property', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_sql.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_sql_migrations_id'), 'api_sql_migrations', ['id'], unique=False)
    op.drop_index('ix_api_model_migrations_id', table_name='api_model_migrations')
    op.drop_table('api_model_migrations')
    op.add_column('api_sql', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('api_sql', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('api_sql', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('api_sql', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('api_sql', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_sql', 'updated_on')
    op.drop_column('api_sql', 'updated_by')
    op.drop_column('api_sql', 'created_on')
    op.drop_column('api_sql', 'created_by')
    op.drop_column('api_sql', 'user_id')
    op.create_table('api_model_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['api_models.id'], name='api_model_migrations_table_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_model_migrations_pkey')
    )
    op.create_index('ix_api_model_migrations_id', 'api_model_migrations', ['id'], unique=False)
    op.drop_index(op.f('ix_api_sql_migrations_id'), table_name='api_sql_migrations')
    op.drop_table('api_sql_migrations')
    op.drop_index(op.f('ix_api_sql_logs_id'), table_name='api_sql_logs')
    op.drop_table('api_sql_logs')
    # ### end Alembic commands ###
