"""coreparams

Revision ID: c8c3d16b1cab
Revises: 32307230d520
Create Date: 2024-03-29 14:27:41.122039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c3d16b1cab'
down_revision: Union[str, None] = '32307230d520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_core', sa.Column('api_header_requests', sa.Text(), nullable=True))
    op.add_column('api_core_migrations', sa.Column('api_header_requests', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_core_migrations', 'api_header_requests')
    op.drop_column('api_core', 'api_header_requests')
    # ### end Alembic commands ###
