""""asa0202_01_01"

Revision ID: cd2e0ddb924b
Revises: bb76d90953dc
Create Date: 2024-03-19 12:10:29.784054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2e0ddb924b'
down_revision: Union[str, None] = 'bb76d90953dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
