"""sc_01_post

Revision ID: cee79a84783d
Revises: 6681c43d5403
Create Date: 2024-07-15 17:47:34.277821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee79a84783d'
down_revision: Union[str, None] = '6681c43d5403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sc_01_post', sa.Column('contact_persons', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sc_01_post', 'contact_persons')
    # ### end Alembic commands ###
