"""Schema field

Revision ID: d14c2621151a
Revises: 2f41a65635bb
Create Date: 2024-03-11 14:05:31.662374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14c2621151a'
down_revision: Union[str, None] = '2f41a65635bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_schema', sa.Column('api_connection_id', sa.Integer(), nullable=True))
    op.add_column('api_schema', sa.Column('api_schemas', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_schema', 'api_schemas')
    op.drop_column('api_schema', 'api_connection_id')
    # ### end Alembic commands ###
