"""0901UPDATE

Revision ID: d1eb0d97126e
Revises: 29f9fdd99a1a
Create Date: 2024-01-09 15:38:29.363507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1eb0d97126e'
down_revision: Union[str, None] = '29f9fdd99a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_models', sa.Column('document_url', sa.String(), nullable=True))
    op.drop_constraint('api_models_cms_page_fkey', 'api_models', type_='foreignkey')
    op.drop_column('api_models', 'cms_uid')
    op.drop_column('api_models', 'cms_api_name')
    op.drop_column('api_models', 'cms_page')
    op.drop_column('api_models', 'cms_file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_models', sa.Column('cms_file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_models', sa.Column('cms_page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('api_models', sa.Column('cms_api_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_models', sa.Column('cms_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('api_models_cms_page_fkey', 'api_models', 'api_cms_page', ['cms_page'], ['id'])
    op.drop_column('api_models', 'document_url')
    # ### end Alembic commands ###
