"""asa0202_01_01

Revision ID: daecd82fd03d
Revises: ab0b176de887
Create Date: 2024-03-28 16:28:07.744087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daecd82fd03d'
down_revision: Union[str, None] = 'ab0b176de887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0202_01_01', 'menu_group_name')
    op.drop_column('asa0202_01_01', 'menu_dropdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('menu_dropdown', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0202_01_01', sa.Column('menu_group_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
