"""country

Revision ID: db2133372f38
Revises: 7d7da47bddeb
Create Date: 2024-04-05 14:10:22.241925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2133372f38'
down_revision: Union[str, None] = '7d7da47bddeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0202_01_01', sa.Column('menu_uid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'asa0202_01_01', ['menu_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asa0202_01_01', type_='unique')
    op.drop_column('asa0202_01_01', 'menu_uid')
    # ### end Alembic commands ###
