""""asa0202_01_01"

Revision ID: e3191a0b6a67
Revises: c548e5e9e034
Create Date: 2024-03-19 22:34:12.298593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3191a0b6a67'
down_revision: Union[str, None] = 'c548e5e9e034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0202_01_01', 'menu_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('asa0202_01_01', 'menu_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asa0202_01_01', 'menu_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asa0202_01_01', 'menu_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
