"""demo

Revision ID: e3367f917c11
Revises: 88e8877e76ee
Create Date: 2024-07-19 15:27:02.091851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3367f917c11'
down_revision: Union[str, None] = '88e8877e76ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('psk_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction_remarks', sa.Text(), nullable=True),
    sa.Column('api_id', sa.String(), nullable=True),
    sa.Column('app_psk_id', sa.Integer(), nullable=True),
    sa.Column('app_uid', sa.String(), nullable=True),
    sa.Column('psk_uid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.String(), nullable=True),
    sa.Column('cancel_on', sa.DateTime(), nullable=True),
    sa.Column('cancel_status', sa.String(), nullable=True),
    sa.Column('cancel_remarks', sa.String(), nullable=True),
    sa.Column('approval_level_1', sa.Integer(), nullable=True),
    sa.Column('approval_level_2', sa.Integer(), nullable=True),
    sa.Column('approval_remarks', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('workflow_role', sa.String(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('gis_latitude', sa.Float(), nullable=True),
    sa.Column('gis_longitude', sa.Float(), nullable=True),
    sa.Column('cdn_location', sa.String(), nullable=True),
    sa.Column('field1', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('psk_id')
    )
    op.create_index(op.f('ix_demo_psk_id'), 'demo', ['psk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_psk_id'), table_name='demo')
    op.drop_table('demo')
    # ### end Alembic commands ###
