"""country

Revision ID: f0de9d350523
Revises: 3f4a04f30e71
Create Date: 2024-06-20 10:29:28.782189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0de9d350523'
down_revision: Union[str, None] = '3f4a04f30e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('demo_8', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'demo_8')
    # ### end Alembic commands ###
