"""NEW VERS

Revision ID: f71a16397fef
Revises: 9a7499deefa7
Create Date: 2023-12-23 11:13:40.417753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71a16397fef'
down_revision: Union[str, None] = '9a7499deefa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_fields', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('api_model_migrations', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('api_model_migrations', sa.Column('fields_list', sa.Text(), nullable=True))
    op.add_column('api_models', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_models', 'version')
    op.drop_column('api_model_migrations', 'fields_list')
    op.drop_column('api_model_migrations', 'version')
    op.drop_column('api_fields', 'archived')
    # ### end Alembic commands ###
