"""asa0203_01_01

Revision ID: f7d64309895f
Revises: 69cfd3c16bc6
Create Date: 2024-03-28 17:01:01.038780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d64309895f'
down_revision: Union[str, None] = '69cfd3c16bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asa0203_01_01', 'menu_privilege_dropdown')
    op.drop_column('asa0203_01_01', 'menu_privilege_href')
    op.drop_column('asa0203_01_01', 'menu_privilege_icon')
    op.drop_column('asa0203_01_01', 'menu_app_bar')
    op.drop_column('asa0203_01_01', 'menu_group_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asa0203_01_01', sa.Column('menu_group_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_app_bar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_href', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asa0203_01_01', sa.Column('menu_privilege_dropdown', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
