"""country

Revision ID: fc6505205f63
Revises: a65ebfce48dc
Create Date: 2024-05-27 15:21:02.765153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6505205f63'
down_revision: Union[str, None] = 'a65ebfce48dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('demo4', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'demo4')
    # ### end Alembic commands ###
