""""assignmenu_roleprivilege"

Revision ID: fede94efe62b
Revises: b22b86ee5127
Create Date: 2023-12-23 11:19:55.514471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fede94efe62b'
down_revision: Union[str, None] = 'b22b86ee5127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
