# Generated by Django 5.0.6 on 2024-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0002_studiomenus_menu_ui_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiomenus',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
