# Generated by Django 5.0.6 on 2024-08-12 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0004_remove_studiomenus_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomenus',
            name='menu_uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
