# Generated by Django 5.0.6 on 2024-08-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0005_alter_studiomenus_menu_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiomenus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
