# Generated by Django 5.0.6 on 2024-08-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0008_apppermissiongroup_apppermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppermission',
            old_name='permission',
            new_name='role',
        ),
    ]
