# Generated by Django 5.0.6 on 2024-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0009_rename_permission_apppermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='group_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
